### PR TITLE
[UX]: Make run status in UI and CLI easier to understand

### LINKED ISSUE #2655: [UX]: Improve the output of `dstack ps`
### Problem

1. The `dstack ps` command doesn't provide termination reason information.
2. The `dstack ps -v` command is too verbose and is not prettified.

Example:

```
vscode               ssh (remote)           cpu=12 mem=30GB disk=26GB               instance                                 $0       terminated  4 weeks ago   STOPPED_BY_USER
 vscode                                                                                                                                terminated  4 weeks ago   STOPPED_BY_USER
 vscode               ssh (remote)           cpu=12 mem=30GB disk=26GB               instance                                 $0       terminated  4 weeks ago   STOPPED_BY_USER
 vscode                                                                                                                                failed      4 weeks ago   JOB_FAILED
                                                                                                                                                                 (FAILED_TO_START_DUE_TO_NO_CAPACITY)
 vscode               ssh (remote)           cpu=12 mem=30GB disk=26GB               instance                                 $0       failed      4 weeks ago   STOPPED_BY_USER
 vscode               ssh (remote)           cpu=12 mem=30GB disk=26GB               instance                                 $0       failed      4 weeks ago   JOB_FAILED
                                                                                                                                                                 (INTERRUPTED_BY_NO_CAPACITY)
 blue-mole-1          nebius (eu-north1)     cpu=2 mem=8GB disk=100GB                cpu-e2 2vcpu-8gb                         $0.0496  done        1 month ago   ALL_JOBS_DONE
 n
```

> Note, the UI should be updated too

Image

3. The `RESERVATION` column takes up too much space while often being empty.

4. If extra space is freed, it can be used to add the `COST` column.

### Solution

1 & 2. Instead of showing run status, pretty-print the run/job termination reason, e.g. in a way, similar to `docker ps`.

Examples:
`STOPPED_BY_USER` -> `stopped`
`INTERRUPTED_BY_NO_CAPACITY` -> `spot interrupted`
`ALL_JOBS_DONE` -> `done`
`CONTAINER_EXITED_WITH_ERROR`  -> `exited (number)`
`FAILED_TO_START_DUE_TO_NO_CAPACITY` -> `no capacity`

This way, we provide more complete information while taking up at least half the space.

3. Merge `RESERVATION` into `INSTANCE`

Example: `<instance type> (<reservation-code>)` or `<instance type> ` if no reservation code is specified 

4. If `-v` is specified, add `COST`

### Workaround

_No response_

### Would you like to help us implement this feature by sending a PR?

Yes

### PR DESCRIPTION
**Pull request by peterschmidt85**
Fixes #2655 

- [x] In the `Status` column (both CLI and UI), show a human-readable status explaining the termination reason from the last job submission  (Example `Failed` -> `Exited (137)`; `Failed` -> `No offers`, etc)
- [x] Correct the status color in UI (e.g. for `Aborted` or `No offers`, use Yellow)
- [x] In the `Error` column (both CLI and UI), show a human-readable status only in case the `Status` information is not enough (e.g. do not show anything in case of `No offers` or `Exited (137)`.
- [x] Merge the `Reservation` column into the `Instance type` column
- [x] Reflect the `Status` changes in the output of `dstack apply` in case the run has failed due to `No offers` or `Exited (X)`

### CODE REVIEW

File: frontend/src/libs/run.ts [hunk 1]
```diff
@@ -25,6 +26,60 @@ export const getStatusIconType = (status: IRun['status']): StatusIndicatorProps[
...
+            return 'yellow'
+        default:
+            return undefined;
+    }
+};
+
+
+const capitalize = (str: string): string => str.charAt(0).toUpperCase() + str.slice(1);
+
+export const getJobSubmissionStatus = (run: IRun): string => {
```
Comment (r4victor) [inline frontend/src/libs/run.ts]: Why duplicating the pretty_repr logic in the frontend/CLI – they'll be likely to diverge. Better to implement it on the server and just show on the CLI/frontend side.

**Review by olgenn — APPROVED** [review]

File: src/dstack/_internal/core/models/runs.py [hunk 2]
```diff
@@ -301,6 +301,81 @@ def duration(self) -> timedelta:
...
+        elif termination_reason == JobTerminationReason.PORTS_BINDING_FAILED:
+            return "ports binding failed"
+        elif termination_reason == JobTerminationReason.CREATING_CONTAINER_ERROR:
+            return "runner error"
+        elif termination_reason == JobTerminationReason.EXECUTOR_ERROR:
+            return "executor error"
+        elif termination_reason == JobTerminationReason.MAX_DURATION_EXCEEDED:
+            return "max duration exceeded"
+        else:
+            return None
```
Comment (r4victor) [inline src/dstack/_internal/core/models/runs.py]: Maybe define a mapping instead of a big if? Also I think we'll forget to update this when adding new termination reasons unless there is a test that checks all reasons are mapped.

Comment (peterschmidt85) [reply src/dstack/_internal/core/models/runs.py]: Fixed, also added tests

File: src/dstack/_internal/cli/services/configurators/run.py [hunk 3]
```diff
@@ -171,7 +166,12 @@ def apply_configuration(
             # We can attach to run multiple times if it goes from running to pending (retried).
             while True:
                 with MultiItemStatus(f"Launching [code]{run.name}[/]...", console=console) as live:
-                    while not _is_ready_to_attach(run):
```
Comment (r4victor) [inline src/dstack/_internal/cli/services/configurators/run.py:174]: Breaks fix #2720
