### PR TITLE
[Internal] Some runner tests fail on macOS 

### LINKED ISSUE #2878: [Internal] Some runner tests fail on macOS
**Steps to reproduce:**

```shell
cd runner
go test -short -race $(go list ./... | grep -v /vendor/)
```

**Actual behaviour:**

```shell
?       github.com/dstackai/dstack/runner/cmd/runner    [no test files]
?       github.com/dstackai/dstack/runner/cmd/shim      [no test files]
?       github.com/dstackai/dstack/runner/consts        [no test files]
?       github.com/dstackai/dstack/runner/internal/api  [no test files]
?       github.com/dstackai/dstack/runner/internal/gerrors      [no test files]
?       github.com/dstackai/dstack/runner/internal/log  [no test files]
?       github.com/dstackai/dstack/runner/internal/runner/api   [no test files]
?       github.com/dstackai/dstack/runner/internal/schemas      [no test files]
ok      github.com/dstackai/dstack/runner/internal/common       1.208s
?       github.com/dstackai/dstack/runner/internal/shim/backends        [no test files]
?       github.com/dstackai/dstack/runner/internal/types        [no test files]
ok      github.com/dstackai/dstack/runner/internal/connections  1.410s
--- FAIL: TestExecutor_WorkingDir_Current (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10358ab60]

goroutine 12 [running]:
testing.tRunner.func1.2({0x1036c8040, 0x103a59ea0})
        /usr/local/go/src/testing/testing.go:1632 +0x2c4
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1635 +0x47c
panic({0x1036c8040?, 0x103a59ea0?})
        /usr/local/go/src/runtime/panic.go:791 +0x124
github.com/dstackai/dstack/runner/internal/executor.(*RunExecutor).SetJob(...)
        /Users/cheptsov/dstack/runner/internal/executor/executor.go:225
github.com/dstackai/dstack/runner/internal/executor.makeTestExecutor(0xc0003149c0)
        /Users/cheptsov/dstack/runner/internal/executor/executor_test.go:196 +0x480
github.com/dstackai/dstack/runner/internal/executor.TestExecutor_WorkingDir_Current(0xc0003149c0)
        /Users/cheptsov/dstack/runner/internal/executor/executor_test.go:24 +0x74
testing.tRunner(0xc0003149c0, 0x1037534a8)
        /usr/local/go/src/testing/testing.go:1690 +0x188
created by testing.(*T).Run in goroutine 1
        /usr/local/go/src/testing/testing.go:1743 +0x5e4
FAIL    github.com/dstackai/dstack/runner/internal/executor     0.240s
--- FAIL: TestGetAMDGPUMetrics_OK (0.00s)
    metrics_test.go:12: 
                Error Trace:    /Users/cheptsov/dstack/runner/internal/metrics/metrics_test.go:12
                Error:          Received unexpected error:
                                could not read /proc/self/mountinfo: open /proc/self/mountinfo: no such file or directory
                Test:           TestGetAMDGPUMetrics_OK
--- FAIL: TestGetAMDGPUMetrics_ErrorGPUUtilNA (0.00s)
    metrics_test.go:43: 
                Error Trace:    /Users/cheptsov/dstack/runner/internal/metrics/metrics_test.go:43
                Error:          Received unexpected error:
                                could not read /proc/self/mountinfo: open /proc/self/mountinfo: no such file or directory
                Test:           TestGetAMDGPUMetrics_ErrorGPUUtilNA
FAIL
FAIL    github.com/dstackai/dstack/runner/internal/metrics      0.402s
ok      github.com/dstackai/dstack/runner/internal/repo 1.331s
ok      github.com/dstackai/dstack/runner/internal/shim 1.593s
ok      github.com/dstackai/dstack/runner/internal/shim/api     1.232s
ok      github.com/dstackai/dstack/runner/internal/shim/dcgm    1.752s
ok      github.com/dstackai/dstack/runner/internal/shim/host    1.412s
FAIL
```

**System info:**

- macOS Sequoia 15.4.1

### PR DESCRIPTION
**Pull request by peterschmidt85**
Fixes #2878

- [x] Add runner-test on macOS in CI/CD 
- [x] Fix runner-test on macOS

### CODE REVIEW

File: runner/internal/executor/executor.go [hunk 1]
```diff
@@ -51,9 +52,20 @@ type RunExecutor struct {
 	timestamp       *MonotonicTimestamp
 
 	killDelay         time.Duration
-	connectionTracker *connections.ConnectionTracker
+	connectionTracker interface {
```
Comment (un-def) [inline runner/internal/executor/executor.go]: It would be better to use a named interface type rather than an inlined one, then you could use that type for `var connectionTracker` below

**Review by un-def — APPROVED** [review]

File: runner/internal/executor/executor.go (hunk 1 above)
Comment (peterschmidt85) [reply runner/internal/executor/executor.go]: Fixed
